name: content-flow
type: typo3
docroot: .Build/Web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false

hooks:
  post-start:
    - exec: composer install --no-interaction
    - exec: composer typo3:setup
    - exec: composer typo3:demo-content
