name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
      - run: composer install --no-progress --no-interaction
      - run: composer cs:check
      - run: composer phpstan

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pdo_sqlite, sqlite3
          coverage: none
      - run: composer install --no-progress --no-interaction
      - run: composer test:unit
      - run: composer test:functional
        env:
          typo3DatabaseDriver: pdo_sqlite
